#!/usr/bin/env sh

echo ""                                                          > README
echo "<!--"                                                     >> README
echo "Generated by:"                                            >> README
echo "$ ./scripts/gen_markdown.sh"                              >> README
echo "-->"                                                      >> README
echo ""                                                         >> README
echo "Official documentation [here](http://lourot.com/gicowa)." >> README
echo ""                                                         >> README

# sudo pip install html2text
html2text README.html                                           >> README
