#!/usr/bin/env sh

echo ""                                                          > README.md
echo "<!--"                                                     >> README.md
echo "Generated by:"                                            >> README.md
echo "$ ./scripts/gen_doc.sh"                                   >> README.md
echo "-->"                                                      >> README.md
echo ""                                                         >> README.md
echo "Official documentation [here](http://lourot.com/gicowa)." >> README.md
echo ""                                                         >> README.md
html2text README.html                                           >> README.md

echo ""                                                          > README
echo ".. Generated by:"                                         >> README
echo "   $ ./scripts/gen_doc.sh"                                >> README
echo ""                                                         >> README
html2rest README.html                                           >> README
