#!/usr/bin/env sh

echo ""                                                          > README.md
echo "<!--"                                                     >> README.md
echo "Generated by:"                                            >> README.md
echo "$ ./scripts/gen_markdown.sh"                              >> README.md
echo "-->"                                                      >> README.md
echo ""                                                         >> README.md
echo "Official documentation [here](http://lourot.com/gicowa)." >> README.md
echo ""                                                         >> README.md

# sudo pip install html2text
html2text README.html                   >> README.md
